/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerDialog.java
 *
 * Created on Feb 28, 2012, 8:19:13 AM
 */
package view;

/**
 *
 * @author Mike
 */
public class CustomerDialog extends javax.swing.JDialog {

    /** Creates new form CustomerDialog */
    public CustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCustomerDialogFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCustomerDialogLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCustomerDialogStreet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCustomerDialogZipCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCustomerDialogCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbCustomerDialogRoute = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jButton2.setText("OK");
        jPanel1.add(jButton2);

        jButton1.setText("Abbrechen");
        jPanel1.add(jButton1);

        jPanel2.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Vorname");
        jPanel2.add(jLabel1);
        jPanel2.add(tfCustomerDialogFirstName);

        jLabel2.setText("Nachname");
        jPanel2.add(jLabel2);
        jPanel2.add(tfCustomerDialogLastName);

        jLabel3.setText("Strasse");
        jPanel2.add(jLabel3);
        jPanel2.add(tfCustomerDialogStreet);

        jLabel4.setText("Postleitzahl");
        jPanel2.add(jLabel4);
        jPanel2.add(tfCustomerDialogZipCode);

        jLabel5.setText("Ort");
        jPanel2.add(jLabel5);
        jPanel2.add(tfCustomerDialogCity);

        jLabel6.setText("Route");
        jPanel2.add(jLabel6);

        cbCustomerDialogRoute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbCustomerDialogRoute);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CustomerDialog dialog = new CustomerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCustomerDialogRoute;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCustomerDialogCity;
    private javax.swing.JTextField tfCustomerDialogFirstName;
    private javax.swing.JTextField tfCustomerDialogLastName;
    private javax.swing.JTextField tfCustomerDialogStreet;
    private javax.swing.JTextField tfCustomerDialogZipCode;
    // End of variables declaration//GEN-END:variables
}
