/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on 06.12.2011, 15:04:21
 */
package view;

/**
 *
 * @author Marco
 */
public class MainView extends javax.swing.JFrame {

    /** Creates new form MainView */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        paCustomer = new javax.swing.JPanel();
        paFunctionsCustomer = new javax.swing.JPanel();
        btAddCustomer = new javax.swing.JButton();
        btEditCustomer = new javax.swing.JButton();
        btRemoveCustomer = new javax.swing.JButton();
        paSearchCustomer = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        cbSearchCustomers = new javax.swing.JComboBox();
        btSearchCustomer = new javax.swing.JButton();
        paTableCustomer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCustomers = new javax.swing.JTable();
        paOrder = new javax.swing.JPanel();
        paFunctionsOrder = new javax.swing.JPanel();
        btAddOrder = new javax.swing.JButton();
        btEditOrder = new javax.swing.JButton();
        btRemoveOrder = new javax.swing.JButton();
        paSearchOrder = new javax.swing.JPanel();
        paSpaceOrder = new javax.swing.JPanel();
        lbCustomerOrder = new javax.swing.JLabel();
        cbCustomerOrder = new javax.swing.JComboBox();
        paTableOrder = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        paRoute = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        paProduct = new javax.swing.JPanel();
        paSearchProduct = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tfSearchProduct = new javax.swing.JTextField();
        btSearchProduct = new javax.swing.JButton();
        paFunctionsProduct = new javax.swing.JPanel();
        btAddProduct = new javax.swing.JButton();
        btEditProduct = new javax.swing.JButton();
        btRemoveProduct = new javax.swing.JButton();
        paTableProduct = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paCustomer.setLayout(new java.awt.BorderLayout());

        paFunctionsCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Funktionen"));
        paFunctionsCustomer.setLayout(new java.awt.GridLayout(1, 0));

        btAddCustomer.setText("Hinzufügen");
        paFunctionsCustomer.add(btAddCustomer);

        btEditCustomer.setText("Bearbeiten");
        btEditCustomer.setEnabled(false);
        paFunctionsCustomer.add(btEditCustomer);

        btRemoveCustomer.setText("Entfernen");
        paFunctionsCustomer.add(btRemoveCustomer);

        paCustomer.add(paFunctionsCustomer, java.awt.BorderLayout.PAGE_END);

        paSearchCustomer.setLayout(new java.awt.GridLayout(1, 3));
        paSearchCustomer.add(tfSearch);

        cbSearchCustomers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paSearchCustomer.add(cbSearchCustomers);

        btSearchCustomer.setText("Suchen");
        paSearchCustomer.add(btSearchCustomer);

        paCustomer.add(paSearchCustomer, java.awt.BorderLayout.PAGE_START);

        paTableCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Kundentabelle"));
        paTableCustomer.setLayout(new java.awt.BorderLayout());

        taCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(taCustomers);

        paTableCustomer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        paCustomer.add(paTableCustomer, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Kunde", paCustomer);

        paOrder.setLayout(new java.awt.BorderLayout());

        paFunctionsOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Funktionen"));
        paFunctionsOrder.setLayout(new java.awt.GridLayout(1, 0));

        btAddOrder.setText("Hinzufügen");
        paFunctionsOrder.add(btAddOrder);

        btEditOrder.setText("Bearbeiten");
        btEditOrder.setEnabled(false);
        paFunctionsOrder.add(btEditOrder);

        btRemoveOrder.setText("Entfernen");
        paFunctionsOrder.add(btRemoveOrder);

        paOrder.add(paFunctionsOrder, java.awt.BorderLayout.PAGE_END);

        paSearchOrder.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout paSpaceOrderLayout = new javax.swing.GroupLayout(paSpaceOrder);
        paSpaceOrder.setLayout(paSpaceOrderLayout);
        paSpaceOrderLayout.setHorizontalGroup(
            paSpaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        paSpaceOrderLayout.setVerticalGroup(
            paSpaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        paSearchOrder.add(paSpaceOrder);

        lbCustomerOrder.setText("Kunden");
        paSearchOrder.add(lbCustomerOrder);

        cbCustomerOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paSearchOrder.add(cbCustomerOrder);

        paOrder.add(paSearchOrder, java.awt.BorderLayout.PAGE_START);

        paTableOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Bestellungstablelle"));
        paTableOrder.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        paTableOrder.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        paOrder.add(paTableOrder, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Bestellung", paOrder);

        paRoute.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jButton1.setText("jButton1");
        jPanel2.add(jButton1);

        jButton2.setText("jButton2");
        jPanel2.add(jButton2);

        jButton3.setText("jButton3");
        jPanel2.add(jButton3);

        paRoute.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("jButton4");
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jButton5.setText("jButton5");
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        paRoute.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Route", paRoute);

        paProduct.setLayout(new java.awt.BorderLayout());

        paSearchProduct.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        paSearchProduct.add(jPanel1);
        paSearchProduct.add(tfSearchProduct);

        btSearchProduct.setText("Suchen");
        paSearchProduct.add(btSearchProduct);

        paProduct.add(paSearchProduct, java.awt.BorderLayout.PAGE_START);

        paFunctionsProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Funktionen"));
        paFunctionsProduct.setLayout(new java.awt.GridLayout(1, 3));

        btAddProduct.setText("Hinzufügen");
        paFunctionsProduct.add(btAddProduct);

        btEditProduct.setText("Bearbeiten");
        btEditProduct.setEnabled(false);
        paFunctionsProduct.add(btEditProduct);

        btRemoveProduct.setText("Entfernen");
        paFunctionsProduct.add(btRemoveProduct);

        paProduct.add(paFunctionsProduct, java.awt.BorderLayout.PAGE_END);

        paTableProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Artikeltabelle"));
        paTableProduct.setLayout(new java.awt.BorderLayout());

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbProduct);

        paTableProduct.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        paProduct.add(paTableProduct, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Artikel", paProduct);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCustomer;
    private javax.swing.JButton btAddOrder;
    private javax.swing.JButton btAddProduct;
    private javax.swing.JButton btEditCustomer;
    private javax.swing.JButton btEditOrder;
    private javax.swing.JButton btEditProduct;
    private javax.swing.JButton btRemoveCustomer;
    private javax.swing.JButton btRemoveOrder;
    private javax.swing.JButton btRemoveProduct;
    private javax.swing.JButton btSearchCustomer;
    private javax.swing.JButton btSearchProduct;
    private javax.swing.JComboBox cbCustomerOrder;
    private javax.swing.JComboBox cbSearchCustomers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCustomerOrder;
    private javax.swing.JPanel paCustomer;
    private javax.swing.JPanel paFunctionsCustomer;
    private javax.swing.JPanel paFunctionsOrder;
    private javax.swing.JPanel paFunctionsProduct;
    private javax.swing.JPanel paOrder;
    private javax.swing.JPanel paProduct;
    private javax.swing.JPanel paRoute;
    private javax.swing.JPanel paSearchCustomer;
    private javax.swing.JPanel paSearchOrder;
    private javax.swing.JPanel paSearchProduct;
    private javax.swing.JPanel paSpaceOrder;
    private javax.swing.JPanel paTableCustomer;
    private javax.swing.JPanel paTableOrder;
    private javax.swing.JPanel paTableProduct;
    private javax.swing.JTable taCustomers;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSearchProduct;
    // End of variables declaration//GEN-END:variables
}
